name: Boosters
version: ${projectVersion}
main: com.willfp.boosters.BoostersPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
depend:
  - eco
softdepend:
  - AureliumSkills
  - Jobs
  - mcMMO
  - Vault
  - TMMobcoins
  - EcoEnchants
  - EcoBosses
  - Talismans
  - EcoArmor
  - EcoItems
  - EcoSkills

commands:
  boosters:
    description: Base Command
    permission: boosters.command.boosters
    aliases:
      - boost

permissions:
  boosters.*:
    description: All boosters permissions
    default: op
    children:
      boosters.command.*: true
  boosters.command.*:
    description: All commands
    default: op
    children:
      boosters.command.reload: true
      boosters.command.give: true
      boosters.command.boosters: true
      boosters.command.cancel: true
      boosters.command.activate: true
      boosters.command.import: true
      boosters.command.export: true

  boosters.command.reload:
    description: Allows reloading the config
    default: op
  boosters.command.boosters:
    description: Allows the use of /boosters.
    default: true
  boosters.command.give:
    description: Allows the use of /boosters give.
    default: op
  boosters.command.activate:
    description: Allows the use of /boosters activate.
    default: op
  boosters.command.cancel:
    description: Allows the use of /boosters cancel.
    default: op
  boosters.command.import:
    description: Allows the use of /boosters import
    default: op
  boosters.command.export:
    description: Allows the use of /boosters export
    default: op